// Generated by `cip build` — do not edit, edit background.py instead.
importScripts("./cip/pyodide/pyodide.js", "./cip/runtime.js");

chrome.runtime.onStartup.addListener(() => {
  self.__cip_registry.startup.forEach((fn) => fn());
});
chrome.runtime.onInstalled.addListener((details) => {
  self.__cip_registry.onInstalled.forEach((fn) => fn(details));
});
if (chrome.commands) {
  chrome.commands.onCommand.addListener((name) => {
    const fn = self.__cip_registry.commands[name];
    if (fn) fn();
  });
}
if (chrome.tabs) {
  chrome.tabs.onCreated.addListener((tab) => {
    self.__cip_registry.onTabCreated.forEach((fn) => fn(tab));
  });
  chrome.tabs.onUpdated.addListener((tabId, changeInfo, tab) => {
    self.__cip_registry.onTabUpdated.forEach((fn) => fn(tabId, changeInfo, tab));
  });
  chrome.tabs.onRemoved.addListener((tabId, removeInfo) => {
    self.__cip_registry.onTabRemoved.forEach((fn) => fn(tabId, removeInfo));
  });
}
if (chrome.alarms) {
  chrome.alarms.onAlarm.addListener((alarm) => {
    self.__cip_registry.onAlarm.forEach((fn) => fn(alarm));
  });
}
chrome.runtime.onMessage.addListener((msg, sender, sendResponse) => {
  const handlers = self.__cip_registry.onMessage;
  if (!handlers || handlers.length === 0) return false;
  Promise.all(handlers.map((fn) => fn(msg, sender))).then((results) => {
    sendResponse(results.find((r) => r !== undefined));
  });
  return true; // keep the message channel open for the async sendResponse
});

// The two array literals below are filled in by `cip build` (project
// python files + vendored dependency wheels, both relative to the
// extension root).
cipInit(__CIP_PY_FILES__, "background", __CIP_DEPENDENCIES__).catch((e) => {
  console.error("[CIP] background init failed:", e);
});
