// Generated by `cip build` — do not edit, edit content.py instead.
// Loaded after cip/pyodide/pyodide.js and cip/runtime.js (see manifest.json
// content_scripts order).
cipInit(__CIP_PY_FILES__, "content", __CIP_DEPENDENCIES__)
  .then(() => {
    const page = { url: location.href, title: document.title };
    (self.__cip_registry.pageLoad || []).forEach((fn) => fn(page));
  })
  .catch((e) => console.error("[CIP] content init failed:", e));
