// Generated by `cip build` — do not edit, edit your options python file instead.
cipInit(__CIP_PY_FILES__, "options", __CIP_DEPENDENCIES__).catch((e) => {
  console.error("[CIP] options init failed:", e);
});
